### ISSUE TITLE
descripe how to test locally without compiling to js first

### ISSUE THREAD

**Issue by tomas259** [pulyaevskiy/firebase-admin-interop#26]

**Comment by pulyaevskiy** [comment]
Short answer: it is not possible to run locally without compiling to JS since this package is a JS interop package.

Long answer:

`firebase_admin_interop` and `firebase_functions_interop` are JS interop packages (hence "interop"). They simply work as wrappers on top of existing JavaScript libraries, respectively `firebase_admin` and `firebase_functions` which are regular NPM packages.

So all of the Firebase functionality actually lives on JS side, unfortunately, and in Dart we have a thin bindings layer to JS APIs plus Dart-specific layer for convenience, it provides API which uses Dart's Futures, Streams and other built-in objects (lists, maps, etc).

So the bad news is: it is not possible to run such apps in Dart VM for testing or debugging purposes.

Also, `firebase_functions` is even trickier as it's a cloud based library so the only real execution environment for functions is on Google servers.

There is good news for `firebase_admin_interop` though. 
It is possible to debug using Node.js after your app is compiled by build_runner.
You can simply run it with node, e.g. `node build/node/main.dart.js`. Or if you need debugging you can use Node.js debugger with `--inspect` flag. Then if you have an IDE which allows connecting to external debug session you can connect to the port printed out by Node.js, add some breakpoints and do you debugging. It actually even picks up all the source maps.

**Comment by pulyaevskiy** [comment]
I'm going to close this as resolved. If you have more questions feel free to submit a new issue.

**Comment by pulyaevskiy** [comment]
@jeremy-dowdall I don't have WebStorm, unfortunately. The way it worked for me in VSCode is that I actually was able to set breakpoints in Dart files, not the JS generated ones.
