### ISSUE TITLE
Firestore support

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/firebase-admin-interop#3]
Hello again...as my main interest is Firestore support, I started implementing it:
https://github.com/tekartik/firebase-admin-interop/commits/master

I tried to follow what you did for Firebase database, however I have some different approach for the data, as Firestore data is not json. Currently i have an approach à la ContentValues on Android where you access each field instead of converting a whole map (which is sometimes impossible as there is no easy way to guess the javascript type of an object). It is not finished yet (it is a side project), however I was wondering whether the implementation I started could ended up being merge into yours at some point, if I should pursue on this or if I should endup with a package layer on top of yours.

I don't know build_value enough to see how it could be integrated with the DocumentData approach I have.

Otherwise I was wondering whether you have any plan to have Firestore support (it is a checkbox in your README!) and the expected timeline.

**Comment by pulyaevskiy** [comment]
Hi Alex,

Thanks again for taking time to create this issue!

First of all, yes, Firestore is a pretty high priority in my list as I'm using it for my project. I was mostly focused on the Flutter side of it at this point though.

That said, I actually was going to spend some time on this and other *_interop packages starting this week, so you had a good timing on this one. :)

The approach you are taking makes sense to me, since Firestore is trying to be more type-aware comparing to Firebase.

I looked briefly at your changes and it is all pretty straightforward. Though I feel we can do a bit better and try to follow Android API more closely. For instance, avoid extra `DocumentData` object and have typed getters/setters on the `DocumentSnapshot` itself.

In any case, if you are willing to contribute your changes, feel free to submit a PR.
From there I can review the code, leave some comments and we can iterate on it to get it merged.

**Comment by alextekartik** [comment]
> For instance, avoid extra DocumentData object and have typed getters/setters on the DocumentSnapshot itself.

I understand what you mean (I have used the API on Android too). Yes similar getter could be set on `DocumentSnapshot` and I will do trying to match the Android API. However when you want to update/set an object, you need an object, with setter, how would you suggest doing this? Ultimately I would love to have a `toObject` and the ability to get/set an object like you did for Firebase. Maybe that's where `built_value` could come into the game. For now I'd like to concentrate on the raw API and will add the getters on `DocumentSnapshot`. I will also look at the flutter firestore API to get some inspiration. Your input is welcome.

I got rid of FieldPath, not having a way to specify multiple functions with the same name and different parameters is a pain here

**Comment by pulyaevskiy** [comment]
> However when you want to update/set an object (DocumentSnapshot are read-only right?), you need an object, with setter, how would you suggest doing this?

Android API provides generic setters on the `DocumentReference`. However that doesn't include typed setters which I suspect what you're trying to achieve?

In this case, something like `DocumentData` is probably unavoidable. Though I'd still prefer if it was immutable and any setter would just return a fresh instance.

I will have some time in the next couple days to play around with this as well. Do you mind if I use your work as a starting point?

**Comment by alextekartik** [comment]
> However that doesn't include typed setters which I suspect what you're trying to achieve?

yes, although we could support generic setter (i support dynamic values in the `Query.where` clause) since we know the type we set

> I will have some time in the next couple days to play around with this as well. Do you mind if I use your work as a starting point?

Of course not, please do if it helps (it is not complete yet though, `Blob` and some other types are missing as well as `DocumentChange` support; `WriteResult` could have a real `DateTime` too). You'll notice that I did not merge firestore in the main `firebase_admin_interop.dart` as I had type conflict on the `Query` type that exists both in firebase database and firestore. I would consider firestore more of an add-on

**Comment by pulyaevskiy** [comment]
Just a quick update. I've started working on a new version here which I'm planning to release eventually as 1.0.0. A few important things:

- It would depend on Dart SDK version >= 2.0 in order to leverage new build system
- It will not rely on Pub transformer anymore but will use `build_runner` package. This allows building with both DDC and dart2js
- I will most likely remove support for built_value (please let me know if you're using this feature)
- I will try to keep API the same when possible.

In regards to Firestore: I already pushed some changes to dart20 branch here with implementation for Firestore which I tried to be as close as possible to what Flutter plugins provide for better UX.

There is one blocking issue I opened for build_runner to support builds for Node, as soon as it resolved I should be able to publish first dev version of 1.0.0 to Pub.

**Comment by alextekartik** [comment]
Thanks for the update. I continued working with my own implementation of Firestore in the mean time (https://github.com/tekartik/firebase-admin-interop). Will move to yours when ready. I was not using built_value so yes please remove it. My only concern is about snapshot data and the usage of jsify/dartify for various types. As you can see in the example https://github.com/tekartik/firebase-admin-interop/blob/master/test/firestore_test.dart#L120-151 personnally, I wrapped the data using an abstract DocumentData to support en/decoding any type. Web javascript firestore client now have weird javascript type detection for Firestore types (Date, Blob...) in dartify/jsify. For writing that's ok, for reading, it is a pain (right now it detects that it is a Date looking for some property https://github.com/firebase/firebase-dart/blob/master/lib/src/utils.dart). It would be good to support any date https://firebase.google.com/docs/firestore/manage-data/data-types but Date is definitely a must

**Comment by pulyaevskiy** [comment]
Thanks again for the feedback. I did end up using `DocumentData` as you can see in the latest changes in `dart20` branch, though I tweaked it a little and also have `UpdateData` to be closer to what Firestore docs are saying. There is already support for `DateTime`, `GeoPoint` and `DocumentReference` types. Still need to add Blob and the whole edge case of arrays with complex types is not covered yet.

**Comment by alextekartik** [comment]
Great. I'm not sure what the setup is now (i tried various commands like `pub run test -p node` and `pub run build_runner test`) as I was not able to use it (dart2.0dev20). I guess instructions will come as you deal on the tooling. Eagerly waiting!

**Comment by pulyaevskiy** [comment]
Yeah, tooling is still in progress. If you're interested in updates you can subscribe to these issues: dart-lang/build#904 and dart-lang/build#959.

I will be updating docs as soon as I get those issues resolved.

**Comment by pulyaevskiy** [comment]
@alextekartik The first 1.0.0-dev version is on Pub with updated docs and examples, just FYI.
